---
version: '3'
services:
  gateway-service:
    build: .
    command: uvicorn src.gateway_service.main:application --host 0.0.0.0 --port 8000 --reload
    container_name: gateway-service
    volumes:
      - .:/gateway-service
    ports:
      - "${LOCAL_APP_PORT:-8000}:8000"
    env_file:
      - .env
